apiVersion: apps/v1
kind: Deployment
metadata:
  name: notification
  namespace: development
  labels:
    app: notification
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 50%
      maxSurge: 50%
  selector:
    matchLabels:
      app: notification
  template:
    metadata:
      namespace: development
      labels:
        app: notification
    spec:
      containers:
      - name: notification
        image: cr.yandex/crpfb8t478v3of681kce/notification:$CIRCLE_SHA1
        ports:
          - containerPort: 4500
        readinessProbe:
          httpGet:
            path: /health
            port: 4500
          initialDelaySeconds: 30
          periodSeconds: 5
          successThreshold: 1
          failureThreshold: 3
        envFrom:
          - configMapRef:
              name: notification-config
      imagePullSecrets:
      - name: gitlabregistrycred
